# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    apiVersion: source.toolkit.fluxcd.io/v1
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 769
        runAsGroup: 769
        runAsNonRoot: true
    controllers:
      bitwarden:
        containers:
          app:
            image:
              repository: ghcr.io/chaijunkin/bw
              tag: 2026.6.0@sha256:23e1a083192845aedc7f4ab23b9cb39929d38268d2e29fe0aa58819c73cbfe1a
            envFrom:
              - secretRef:
                  name: bitwarden-cli
            securityContext:
              readOnlyRootFilesystem: true
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  periodSeconds: 120
                  exec:
                    command:
                      - sh
                      - -c
                      - /healthcheck.sh
                  timeoutSeconds: 5
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
    service:
      app:
        controller: bitwarden
        ports:
          http:
            port: 8087
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
