# yaml-language-server: $schema=https://crd.cloudjur.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-cloud
  labels:
    dashboards: grafana-cloud
spec:
  external:
    adminPassword:
      key: GF_SECURITY_ADMIN_PASSWORD
      name: grafana-secret
    adminUser:
      key: GF_SECURITY_ADMIN_USER
      name: grafana-secret
    url: https://chaijunkin.grafana.net # Placeholder URL
