---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-off-deck
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: plex-off-deck-secret
    template:
      data:
        config.ini: |-
          [auth]
          server_baseurl = http://plex.media.svc.cluster.local:32400
          server_token   = {{ .PLEX_TOKEN }}
  data:
    - secretKey: PLEX_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a3698a58-d1de-4fa5-8070-2784feda47e1
        property: PLEX_TOKEN
