# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-hostpath
