apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: ai
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8081
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: whisper
  namespace: ai
subsets:
  - addresses:
      - ip: 192.168.1.149
    ports:
      - name: http
        port: 8081
