---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  refreshInterval: 15m
  target:
    name: garage-secret
    template:
      templateFrom:
        - configMap:
            name: garage-configmap
            items:
              - key: garage.toml
  data:
    - secretKey: GARAGE_RPC_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GARAGE_RPC_SECRET
    - secretKey: GARAGE_ADMIN_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GARAGE_ADMIN_TOKEN
    - secretKey: GARAGE_METRICS_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GARAGE_METRICS_TOKEN
