# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-external-access
  namespace: observability
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: observability-external-access
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: loki
      namespace: observability
    - name: tempo
      namespace: observability
    - name: pyroscope
      namespace: observability
    - name: grafana
      namespace: observability
  path: ./kubernetes/apps/observability/external-access/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 10m
  suspend: true # Toggle this to false to enable external access
