# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
  namespace: &namespace dev
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/anubis
  dependsOn:
    - name: openebs
      namespace: storage
    - name: dragonfly-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/dev/forgejo/app
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CAPACITY: 10Gi
      ANUBIS_TARGET: http://forgejo-http.dev.svc.cluster.local:3000
      ANUBIS_MEM_LIMIT: 384Mi
      APP_KEY_ID: "6371b847-50bf-4ac2-90ae-6cf2f41e5e68"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
  namespace: dev
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: forgejo
  dependsOn:
    - name: forgejo
      namespace: dev
  interval: 1h
  path: ./kubernetes/apps/dev/forgejo/runner
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dev
  timeout: 5m
  wait: false
