# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${KOPIUR_CLAIM:-${APP}}
spec:
  accessModes: ["${KOPIUR_ACCESSMODES:-ReadWriteOnce}"]
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: ${APP}
  resources:
    requests:
      storage: ${KOPIUR_CAPACITY:=2Gi}
  storageClassName: ${KOPIUR_STORAGECLASS:-miroir-local}
