apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: ${APP}
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  mover:
    securityContext:
      runAsUser: ${KOPIUR_PUID:=2000}
      runAsGroup: ${KOPIUR_PGID:=2000}
  credentialProjection:
    enabled: true
  policy:
    onMissingSnapshot: Continue
  source:
    fromPolicy:
      name: ${APP}
      offset: 0
  target:
    populator: {}
