apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
  annotations:
    kopiur.home-operations.com/allow-identity-change: "true"
spec:
  compression:
    compressor: zstd
  credentialProjection:
    enabled: true
  mover:
    securityContext:
      runAsUser: ${KOPIUR_PUID:=2000}
      runAsGroup: ${KOPIUR_PGID:=2000}
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepDaily: 7
    keepHourly: 24
    keepLatest: 3
    keepWeekly: 4
  sources:
    - pvc:
        name: ${KOPIUR_CLAIM:-${APP}}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=local-hostpath}
