---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        VPN_ENDPOINT_IP: "{{ .VPN_ENDPOINT_IP }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        OPN_API_KEY: "{{ .opnsense_apikey }}"
        OPN_API_SECRET: "{{ .opnsense_apisecret }}"
  data:
    - secretKey: opnsense_apikey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 54e15386-555d-460b-8004-f476af1519ad
        property: admin_api_key
    - secretKey: opnsense_apisecret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 54e15386-555d-460b-8004-f476af1519ad
        property: admin_api_key_secret
    - secretKey: VPN_ENDPOINT_IP
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f28a7000-9e7b-47b4-91db-3afce8393773
        property: qbittorrent_vpn_endpoint_ip
    - secretKey: WIREGUARD_PUBLIC_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f28a7000-9e7b-47b4-91db-3afce8393773
        property: qbittorrent_wireguard_public_key
    - secretKey: WIREGUARD_PRIVATE_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f28a7000-9e7b-47b4-91db-3afce8393773
        property: qbittorrent_wireguard_private_key
    - secretKey: WIREGUARD_ADDRESSES
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f28a7000-9e7b-47b4-91db-3afce8393773
        property: qbittorrent_wireguard_addresses
