---
# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deepwiki-mcp
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: deepwiki-mcp
  path: ./kubernetes/apps/ai/toolhive/mcp-servers/deepwiki-mcp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
