# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-livesync-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        COUCHDB_USER: "{{ .COUCHDB_USER }}"
        COUCHDB_PASSWORD: "{{ .COUCHDB_PASSWORD }}"
  refreshInterval: 12h
  data:
    - secretKey: COUCHDB_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        # TODO: replace with the Bitwarden item ID holding the CouchDB admin credentials
        key: 3aec103d-6f3e-4acf-b8cf-9ac2c51c4111
        property: username
    - secretKey: COUCHDB_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3aec103d-6f3e-4acf-b8cf-9ac2c51c4111
        property: password
