apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-vault-smb-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: default-vault-smb
    volumeAttributes:
      source: "//jk-mac-mini.cloudjur.com/Macintosh HD/Users/jkchai/Documents/DefaultVault"
    nodeStageSecretRef:
      name: default-vault-smb-secret
      namespace: default
