# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-remote-secret
spec:
  target:
    name: kopiur-remote-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  data:
    - secretKey: R2_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cb424eb9-ca32-4608-93ef-63e28c3f531e
        property: r2_access_key
    - secretKey: R2_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cb424eb9-ca32-4608-93ef-63e28c3f531e
        property: r2_access_secret
    - secretKey: KOPIA_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e93b40f5-5416-4fa9-9c04-97390bfcfd39
        property: kopia_password
