---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: picoshare-secret
  namespace: default
spec:
  refreshInterval: 12h
  target:
    name: picoshare
    template:
      data:
        PS_SHARED_SECRET: "{{ .PICOSHARE_SECRET }}"
  data:
    - secretKey: PICOSHARE_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_PICOSHARE
        property: PS_SHARED_SECRET
