---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-sdk-server-secret
            namespace: external-secrets
      caProvider:
        name: bitwarden-sdk-server-cert
        type: Secret
        namespace: external-secrets
        key: ca.crt
      organizationID: b00061df5-6a65-450d-8f61-b43900cf71b8
      projectID: ce1d4ee3-2738-4606-9f57-b4590093f615
