# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-sdk-server
spec:
  # secretStoreRef:
  #   kind: ClusterSecretStore
  #   name: bitwarden-secretsmanager
  target:
    name: bitwarden-sdk-server-secret
    template:
      data:
        token: "{{ .access_token }}"
  data:
    - secretKey: access_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a7b1cb37-9e1d-4127-8b3a-24928e984ead
        property: access_token
