# yaml-language-server: $schema=https://crd.cloudjur.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: remote
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-remote-secret
          namespace: storage
      endpoint: 8550295d25a8172e9fe4f9f7a7f327be.r2.cloudflarestorage.com
      region: auto
      bucket: kopia
  credentialProjection:
    allowed: true
  encryption:
    passwordSecretRef:
      name: kopiur-remote-secret
      namespace: storage
      key: KOPIA_PASSWORD
  create:
    enabled: true # Step 1, then disable this
  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: policyName
  catalog:
    adoption: Ignore
  scheduleDefaults:
    timezone: Asia/Kuala_Lumpur
