# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterrepository.yaml
  - ./externalsecret-r2.yaml
  - ./clusterrepository-r2.yaml
