---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kubernetes-schemas
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        CLOUDFLARE_API_TOKEN: "{{ .GITHUB_PAGES }}"
        CLOUDFLARE_ACCOUNT_ID: "{{ .ACCOUNT_ID }}"
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cb424eb9-ca32-4608-93ef-63e28c3f531e
        property: account_id
    - secretKey: CLOUDFLARE_API_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 153f8e3f-cf1d-4ac6-af96-b934baab3bc5
        property: cloudflare_page_token
