# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: staticgarage-terraform
spec:
  refreshInterval: 1h
  target:
    name: staticgarage-terraform-secret
    template:
      type: Opaque
      data:
        STATICGARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
  data:
    - secretKey: GARAGE_ADMIN_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GARAGE_ADMIN_TOKEN
