# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name trek-mcp-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        MCP_API_TOKEN: "{{ .TREK_API_TOKEN }}"
  data:
    - secretKey: TREK_API_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: trek_mcp_api_token
