# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name trek-mcp-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .TREK_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .TREK_CLIENT_SECRET }}"
  data:
    - secretKey: TREK_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: trek_mcp_oauth_client_id
    - secretKey: TREK_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: trek_mcp_oauth_client_secret
