# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ollama
  namespace: ai
spec:
  targetNamespace: ai
  path: ./kubernetes/apps/ai/ollama/app
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: ollama
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 24h
  retryInterval: 1m

  postBuild:
    substitute:
      APP: ollama
  dependsOn:
    - name: local-hostpath
      namespace: storage
