---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-mcp-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_PAT }}"
  data:
    - secretKey: GITHUB_PAT
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b67e4583-a622-4cf2-a172-58ee67c703da
        property: github-mcp
