---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name context7-mcp-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        CONTEXT7_API_KEY: "{{ .CONTEXT7_API_KEY }}"
  data:
    - secretKey: CONTEXT7_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f70e550d-01b3-4ab7-8329-339461d33741
        property: context7-api-key
