# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name workadventure
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENID_CLIENT_ID: "{{ .WORKADVENTURE_OIDC_CLIENT_ID }}"
        OPENID_CLIENT_SECRET: "{{ .WORKADVENTURE_OIDC_CLIENT_SECRET }}"
        OPENID_CLIENT_ISSUER: "https://auth.cloudjur.com/application/o/workadventure/"
        SECRET_KEY: "{{ .WORKADVENTURE_SECRET_KEY }}"
        MAP_STORAGE_API_TOKEN: "{{ .WORKADVENTURE_MAP_STORAGE_TOKEN }}"
        AUTHENTICATION_PASSWORD: "{{ .WORKADVENTURE_MAPSTORAGE_AUTH_PASSWORD }}"
        MATRIX_ADMIN_PASSWORD: "{{ .MATRIX_ADMIN_PASSWORD }}"
        TURN_STATIC_AUTH_SECRET: "{{ .WORKADVENTURE_TURN_AUTH_SECRET }}"
  refreshInterval: 12h
  data:
    - secretKey: WORKADVENTURE_OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_OIDC_CLIENT_ID
    - secretKey: WORKADVENTURE_OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_OIDC_CLIENT_SECRET
    - secretKey: WORKADVENTURE_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_SECRET_KEY
    - secretKey: WORKADVENTURE_MAP_STORAGE_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_MAP_STORAGE_TOKEN
    - secretKey: WORKADVENTURE_MAPSTORAGE_AUTH_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_MAPSTORAGE_AUTH_PASSWORD
    - secretKey: MATRIX_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 08893da1-da5f-4c3b-b1d8-ab63cd0f5217
        property: MATRIX_ADMIN_PASSWORD
    - secretKey: WORKADVENTURE_TURN_AUTH_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_TURN_AUTH_SECRET
