# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: policy-reporter-smtp
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        host: "{{ .SMTP_HOST }}"
        port: "465"
        username: "{{ .SMTP_USERNAME }}"
        password: "{{ .SMTP_PASSWORD }}"
        from: "{{ .SMTP_FROM }}"
        encryption: ssl/tls
  refreshInterval: 15m
  data:
    - secretKey: SMTP_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_HOST
    - secretKey: SMTP_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_PASSWORD
    - secretKey: SMTP_FROM
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_FROM
