apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: monitor-etc-shadow
spec:
  kprobes:
    - call: security_file_permission
      syscall: false
      args:
        - index: 0
          type: file
        - index: 1
          type: int
      selectors:
        - matchArgs:
            - index: 0
              operator: Equal
              values:
                - /etc/shadow
                - /etc/passwd
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: egress-network-monitor
spec:
  kprobes:
    - call: tcp_connect
      syscall: false
      args:
        - index: 0
          type: sock
    - call: tcp_close
      syscall: false
      args:
        - index: 0
          type: sock
    - call: tcp_sendmsg
      syscall: false
      args:
        - index: 0
          type: sock
        - index: 2
          type: int
