---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.37.0
  replicas: 1
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
    # - name: AWS_ACCESS_KEY_ID
    #   valueFrom:
    #     secretKeyRef:
    #       key: AWS_ACCESS_KEY_ID
    #       name: dragonfly-secret
    # - name: AWS_SECRET_ACCESS_KEY
    #   valueFrom:
    #     secretKeyRef:
    #       key: AWS_SECRET_ACCESS_KEY
    #       name: dragonfly-secret
  # snapshot:
  #   dir: "s3://dragonfly"
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    # - --s3_endpoint=s3.cloudjur.com
  # topologySpreadConstraints:
  #   - maxSkew: 1
  #     topologyKey: kubernetes.io/hostname
  #     whenUnsatisfiable: DoNotSchedule
  #     labelSelector:
  #       matchLabels:
  #         app.kubernetes.io/part-of: dragonfly
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
  serviceSpec:
    annotations:
      gatus.home-operations.com/enabled: "true"
      gatus.home-operations.com/endpoint: |
        conditions:
          - "[CONNECTED] == true"
        group: services
        ui:
          hide-hostname: true
          hide-url: true
        alerts:
          - type: pushover
            send-on-resolved: true
