# yaml-language-server: $schema=https://crd.cloudjur.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.39.0
  replicas: 1
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor:
            1Mi
            # - name: AWS_ACCESS_KEY_ID
            #   valueFrom:
            #     secretKeyRef:
            #       key: AWS_ACCESS_KEY_ID
            #       name: dragonfly-secret
            # - name: AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       key: AWS_SECRET_ACCESS_KEY
            #       name: dragonfly-secret
  # snapshot:
  #   dir: "s3://dragonfly"
  args:
    - --admin_bind=0.0.0.0
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=1
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --default_lua_flags=allow-undeclared-keys
      # - --s3_endpoint=s3.cloudjur.com
  # topologySpreadConstraints:
  #   - maxSkew: 1
  #     topologyKey: kubernetes.io/hostname
  #     whenUnsatisfiable: DoNotSchedule
  #     labelSelector:
  #       matchLabels:
  #         app.kubernetes.io/part-of: dragonfly
  labels:
    role: master

  networkPolicyEnabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
  serviceSpec:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 10.10.30.8
      gatus.home-operations.com/enabled: "true"
      gatus.home-operations.com/endpoint: |
        conditions:
          - "[CONNECTED] == true"
        group: services
        ui:
          hide-hostname: true
          hide-url: true
        alerts:
          - type: pushover
            send-on-resolved: true
