---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  refreshInterval: 15m
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GAGAGE_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GAGAGE_SECRET_KEY
