---
serviceMonitor:
  create: true
web:
  config:
    authentication:
      type: Anonymous
      anonymous:
        username: flux
        groups:
          - flux-admin
  httpRoute:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Platform Infrastructure
      gethomepage.dev/name: Flux Operator
      gethomepage.dev/icon: flux.png
    hostnames:
      - flux-operator.cloudjur.com
    parentRefs:
      - name: envoy-internal
        namespace: network
  networkPolicy:
    create: false
