---
serviceMonitor:
  create: true
web:
  config:
    authentication:
      type: Anonymous
      anonymous:
        username: flux
        groups:
          - flux-admin
  httpRoute:
    enabled: true
    hostnames:
      - flux-operator.cloudjur.com
    parentRefs:
      - name: envoy-internal
        namespace: network
  networkPolicy:
    create: false