# yaml-language-server: $schema=https://crd.cloudjur.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: &app konflate
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.1
  url: oci://ghcr.io/home-operations/charts/konflate
---
# yaml-language-server: $schema=https://crd.cloudjur.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app konflate
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    config:
      repo: github://chaijunkin/home-ops
      statusChecks: true
      prComments: true
      verifyImages: true
      mcp: true
      publicUrl: https://konflate.cloudjur.com
    secret:
      existingSecret: konflate-secret
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          conditions: ["[STATUS] == 200"]
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames:
        - konflate.cloudjur.com
    monitoring:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 2Gi
