# yaml-language-server: $schema=https://crd.cloudjur.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        # - downstairs-hallway-slzb06.cloudjur.com
        # - garage-tablet.cloudjur.com
        # - gladius.cloudjur.com
        # - hallway-tablet.cloudjur.com
        # - livingroom-vacuum.cloudjur.com
        - smb.cloudjur.com
        - pikvm.cloudjur.com
        - plv.cloudjur.com # piano led visualizer
        - gateway.cloudjur.com
          # - pikvm.cloudjur.com
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
---
# yaml-language-server: $schema=https://crd.cloudjur.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - smb.cloudjur.com:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
