[b2]
type = s3
account = {{ .B2_ACCESS_KEY_ID }}
key = {{ .B2_SECRET_ACCESS_KEY }}
endpoint = {{ .B2_ENDPOINT }}
provider = Other
region = {{ .B2_REGION }}

[garage]
type = s3
provider = Other
region = us-east-1
env_auth = false
access_key_id = "{{ .GARAGE_ACCESS_KEY_ID }}"
secret_access_key = "{{ .GARAGE_SECRET_ACCESS_KEY }}"
endpoint = https://s3.cloudjur.com
force_path_style = true
acl = private
bucket_acl = private
# sign_accept_encoding = false
# s3_sign_accept_encoding = false
# no_check_bucket = true