# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ark-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ARK_SERVER_PASSWORD: "{{ .SERVER_PASSWORD }}"
        ARK_SERVER_RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
        ARK_SERVER_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  data:
    - secretKey: SERVER_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b9d9b91-c0a4-47d5-be93-b8e082a64cbf
        property: server-password
    - secretKey: RCON_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b9d9b91-c0a4-47d5-be93-b8e082a64cbf
        property: rcon-password
    - secretKey: ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b9d9b91-c0a4-47d5-be93-b8e082a64cbf
        property: admin-password
