null
---
# yaml-language-server: $schema=https://crd.cloudjur.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.22.2
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
---
# yaml-language-server: $schema=https://crd.cloudjur.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  chartRef:
    kind: OCIRepository
    name: grafana-operator
  interval: 24h
  values:
    dashboard:
      enabled: true
    serviceMonitor:
      enabled: true
{
log_level: warning
authentik_host: https://auth.cloudjur.com
kubernetes_replicas: 1
kubernetes_namespace: observability
object_naming_template: ak-outpost-%(name)s
kubernetes_service_type: ClusterIP
kubernetes_disabled_components:
  - ingress
kubernetes_httproute_annotations:
  gatus.home-operations.com/enabled: "false"
kubernetes_httproute_parent_refs:
  - kind: Gateway
    name: envoy-external
    group: gateway.networking.k8s.io
    namespace: network
    sectionName: https
}