# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-automation
spec:
  refreshInterval: 12h
  target:
    name: zigbee2mqtt-secret
    template:
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
          "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
          }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID:
          "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
          }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
          "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
          }}"
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .MQTT_USERNAME }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
  data:
    - secretKey: MQTT_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9e81dd94-1b00-4f9b-be20-1cc468446d29
        property: username
    - secretKey: MQTT_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9e81dd94-1b00-4f9b-be20-1cc468446d29
        property: password
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_ZIGBEE
        property: ext_pan_id
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_ZIGBEE
        property: pan_id
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_ZIGBEE
        property: network_key
