# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: memini-secret
    creationPolicy: Owner
    template:
      data:
        MEMINI_API_KEY: "{{ .memini_api_key }}"
        MEMINI_EMBED_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        MEMINI_LLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        MEMINI_RERANK_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
  data:
    - secretKey: memini_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5b8f5c59-8a9c-495b-9f40-9ea2a2ab249f
        property: api_key
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bf2fcc14-bd51-4122-9445-53dacdfb1d69
        property: LITELLM_MASTER_KEY
