---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: memini-secret
    creationPolicy: Owner
    template:
      data:
        MEMINI_API_KEY: "{{ .memini_api_key }}"
  data:
    - secretKey: memini_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5b8f5c59-8a9c-495b-9f40-9ea2a2ab249f
        property: api_key
