---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cjk-bot-pem
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PRIVATE_KEY: "{{ .ACTIONS_RUNNER_PRIVATE_KEY }}"
  data:
    - secretKey: ACTIONS_RUNNER_PRIVATE_KEY
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: fd77a223-2367-4076-a71e-b34bef8c9268
---
# yaml-language-server: $schema=https://crd.cloudjur.com/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: cjk-bot-auth-token
spec:
  appID: "853106"
  installID: "48266880"
  auth:
    privateKey:
      secretRef:
        name: cjk-bot-pem # reference secret from step 1.
        key: PRIVATE_KEY
---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cjk-bot-token
spec:
  refreshInterval: "30m0s"
  target:
    name: cjk-bot-token
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: aXNoaW9uaQ==
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: cjk-bot-auth-token
