# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      data:
        token: "{{ .forgejo_runner_token }}"
        uuid: "{{ .forgejo_runner_uuid }}"
  data:
    - secretKey: forgejo_runner_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 741ab874-d619-4bed-a307-8b67ea13f4c1
        property: runner_token
    - secretKey: forgejo_runner_uuid
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 741ab874-d619-4bed-a307-8b67ea13f4c1
        property: runner_uuid
