# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sparkyfitness-mcp-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        SPARKY_FITNESS_API_KEY: "{{ .SPARKY_FITNESS_API_KEY }}"
  data:
    - secretKey: SPARKY_FITNESS_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0f0ab97a-8e58-4c98-b6f2-00bdd1e62f93
        property: mcp_key
