# yaml-language-server: $schema=https://crd.cloudjur.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: sparkyfitness-mcp
spec:
  image: node:24-alpine
  transport: stdio
  groupRef:
    name: mcp-tools
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          securityContext:
            readOnlyRootFilesystem: false
          env:
            - name: SPARKY_FITNESS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-mcp-secret
                  key: SPARKY_FITNESS_API_KEY
          command:
            - npx
          args:
            - -y
            - mcp-remote
            - http://sparkyfitness-server.default.svc.cluster.local:3010/mcp
            - --allow-http
            - --transport
            - http-only
            - --header
            - "Authorization: Bearer $(SPARKY_FITNESS_API_KEY)"
