# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-terraform
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: authentik-terraform-secret
    # template:
    #   engineVersion: v2
    #   data:
    #     # --- Shared ---
    #     public_domain: cloudjur.com # Hardcoded based on repo analysis

    #     # --- Authentik Core ---
    #     authentik_token: "{{ .AUTHENTIK_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: TF_VAR_.*

