# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omada-exporter-secret
spec:
  target:
    name: omada-exporter-secret
    template:
      data:
        OMADA_USER: "{{ .OMADA_USER }}"
        OMADA_PASS: "{{ .OMADA_PASS }}"
        OMADA_SITE: Default
  data:
    - secretKey: OMADA_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9f2b46a5-9d21-46c9-b4e8-6102f27938f8
        property: username
    - secretKey: OMADA_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9f2b46a5-9d21-46c9-b4e8-6102f27938f8
        property: password
