---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-secret
spec:
  refreshInterval: 5m
  target:
    name: toolhive-secret
    creationPolicy: Owner
    template:
      data:
        signing_key: "{{ .toolhive_auth_server_signing_key }}"
        hmac_key: "{{ .toolhive_auth_server_hmac_key }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: toolhive_auth_server_signing_key
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 37b53ec8-b4bf-4fdb-a868-0772129679d9
        property: signing_key
    - secretKey: toolhive_auth_server_hmac_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 37b53ec8-b4bf-4fdb-a868-0772129679d9
        property: hmac_key
    - secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 37b53ec8-b4bf-4fdb-a868-0772129679d9
        property: OIDC_CLIENT_SECRET
