---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpoidcconfig_1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPOIDCConfig
metadata:
  name: authentik
spec:
  type: inline
  inline:
    issuer: https://mcp.cloudjur.com
    jwksAllowPrivateIP: true
    # protectedResourceAllowPrivateIP: true
