---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway
spec:
  authServerConfig:
    issuer: https://auth.cloudjur.com
    signingKeySecretRefs:
      - name: toolhive-secret
        key: signing_key
    hmacSecretRefs:
      - name: toolhive-secret
        key: hmac_key
    tokenLifespans:
      accessTokenLifespan: 1h
      refreshTokenLifespan: 168h
      authCodeLifespan: 10m
    upstreamProviders:
      - name: authentik
        type: oidc
        oidcConfig:
          issuerUrl: https://auth.cloudjur.com/application/o/toolhive/
          clientId: toolhive
          clientSecretRef:
            name: toolhive-secret
            key: OIDC_CLIENT_SECRET
          redirectUri: https://mcp.cloudjur.com/oauth/callback
          scopes:
            - openid
            - profile
            - email
            - offline_access
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}."
  telemetryConfigRef:
    name: prometheus
  groupRef:
    name: mcp-tools
  incomingAuth:
    type: oidc
    oidcConfigRef:
      name: authentik
      audience: https://auth.cloudjur.com/mcp
      resourceUrl: https://auth.cloudjur.com/mcp
      scopes:
        - openid
        - profile
        - email
        - offline_access
  outgoingAuth:
    source: discovered
  sessionStorage:
    address: dragonfly.database.svc.cluster.local:6379
    db: 9
    provider: redis
    keyPrefix: "vmcp-sessions:"
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          env:
            - name: INSECURE_DISABLE_URL_VALIDATION
              value: "true"
---
# yaml-language-server: $schema=https://crd.movishell.pl/toolhive.stacklok.dev/virtualmcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-internal
spec:
  config:
    groupRef: mcp-tools
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}."
  groupRef:
    name: mcp-tools
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
  telemetryConfigRef:
    name: prometheus
