# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./convertx/ks.yaml
  - ./cyberchef/ks.yaml
    # - ./changedetection/ks.yaml
    # - ./freshrss/ks.yaml
  - ./glance/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
    # - ./karakeep/ks.yaml
  - ./n8n/ks.yaml
    # - ./pdf-tool/ks.yaml
  - ./paperless/ks.yaml
  - ./rustdesk/ks.yaml
  - ./searxng/ks.yaml
  - ./sure/ks.yaml
    # - ./thelounge/ks.yaml
  - ./tika/ks.yaml
  - ./picoshare/ks.yaml
    # - ./smtp-relay/ks.yaml
  - ./trek/ks.yaml
