# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: staticgarage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: staticgarage-secret
    template:
      engineVersion: v2
      data:
        garage.toml: |
          {{ .garage_toml | replace "{{ .STATICGARAGE_RPC_SECRET }}" .STATICGARAGE_RPC_SECRET | replace "{{ .STATICGARAGE_ADMIN_TOKEN }}" .STATICGARAGE_ADMIN_TOKEN | replace "{{ .STATICGARAGE_METRICS_TOKEN }}" .STATICGARAGE_METRICS_TOKEN }}
  dataFrom:
    - extract:
        key: staticgarage
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ConfigMap
          name: staticgarage-configmap
