# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocharted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: ocharted-secret
    template:
      data:
        auth: "{{ .OCHARTED_USERNAME }}:{{ .OCHARTED_PASSWORD }}"
  data:
    - secretKey: OCHARTED_USERNAME
      remoteRef:
        key: REPLACE_WITH_UUID
        property: username
    - secretKey: OCHARTED_PASSWORD
      remoteRef:
        key: REPLACE_WITH_UUID
        property: password
