# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name miso-chat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: *name
    template:
      data:
        ## OAUTH
        OIDC_ENABLED: "true"
        OIDC_ISSUER: https://auth.cloudjur.com
        OIDC_PROVIDER_URL: https://auth.cloudjur.com/application/o/miso-chat/.well-known/openid-configuration
        OIDC_PROVIDER_NAME: Authentik
        OIDC_CLIENT_ID: "{{ .MISO_CHAT_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MISO_CHAT_CLIENT_SECRET }}"
        OIDC_CALLBACK_URL: https://miso-chat.cloudjur.com/auth/oidc/callback
        ## MISO-CHAT
        SESSION_SECRET: "{{ .MISO_SESSION_SECRET }}"
        ## OPENCLAW
        GATEWAY_URL: ws://openclaw.ai.svc.cluster.local:18789
        GATEWAY_AUTH_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
  data:
    - secretKey: MISO_CHAT_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT
        property: MISO_CHAT_CLIENT_ID
    - secretKey: MISO_CHAT_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT
        property: MISO_CHAT_CLIENT_SECRET
    - secretKey: MISO_SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT
        property: MISO_SESSION_SECRET
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT
        property: OPENCLAW_GATEWAY_TOKEN
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name miso-chat-device
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: *name
    template:
      data:
        ## OpenClaw configuration file
        device.json: |
          {
            "version": 1,
            "deviceId": "{{ .DEVICE_ID }}",
            "publicKeyPem": "{{ .PUBLIC_KEY_PEM }}",
            "privateKeyPem": "{{ .PRIVATE_KEY_PEM }}",
            "createdAtMs": 1772054304137
          }
  data:
    - secretKey: DEVICE_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT_DEVICE
        property: DEVICE_ID
    - secretKey: PUBLIC_KEY_PEM
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT_DEVICE
        property: PUBLIC_KEY_PEM
    - secretKey: PRIVATE_KEY_PEM
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_MISOCHAT_DEVICE
        property: PRIVATE_KEY_PEM
