# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./toolhive/mcp-servers/context7-mcp/ks.yaml
  - ./toolhive/mcp-servers/github-mcp/ks.yaml
  - ./toolhive/mcp-servers/grafana-mcp/ks.yaml
  - ./toolhive/mcp-servers/ha-mcp/ks.yaml
  - ./toolhive/mcp-servers/kubectl-mcp/ks.yaml
  - ./toolhive/mcp-servers/flux-mcp/ks.yaml
    # - ./toolhive/mcp-servers/comfyui-mcp/ks.yaml
    # - ./toolhive/mcp-servers/memory-mcp/ks.yaml
    # - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
  - ./toolhive/mcp-servers/searxng-mcp/ks.yaml
  - ./toolhive/ks.yaml
  - ./toolhive/mcp-servers/fli-mcp/ks.yaml
  - ./toolhive/mcp-servers/deepwiki-mcp/ks.yaml
  # - ./toolhive/mcp-servers/sure-mcp/ks.yaml
  # - ./toolhive/mcp-servers/trek-mcp/ks.yaml
    # - ./comfyui/ks.yaml
    # - ./hermes/ks.yaml
    # - ./openclaw/ks.yaml
    # - ./litellm/ks.yaml
    # - ./memini/ks.yaml
    # - ./llmkube/ks.yaml
