---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp
spec:
  target:
    name: ha-mcp-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        HOMEASSISTANT_TOKEN: "{{ .HASS_TOKEN }}"
  refreshInterval: 15m
  data:
    - secretKey: HASS_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 408d35a8-f63a-4660-8e5a-198c3c4bbc32
        property: HASS_TOKEN
