# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qui
  namespace: downloads
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: qui
  path: ./kubernetes/apps/downloads/qui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 24h
  retryInterval: 1m

  postBuild:
    substitute:
      APP: qui
      # KOPIUR_PUID: "1000"
      # KOPIUR_PGID: "1000"
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/volsync
    # - ../../../../components/kopiur/backup
    # - ../../../../components/kopiur/adhoc-snapshot
  dependsOn:
    - name: openebs
      namespace: storage
