# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name coturn
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TURN_STATIC_AUTH_SECRET: "{{ .WORKADVENTURE_TURN_AUTH_SECRET }}"
  refreshInterval: 1h
  data:
    - secretKey: WORKADVENTURE_TURN_AUTH_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 623fe504-8737-42d4-b085-cfa0dc6a4b94
        property: WORKADVENTURE_TURN_AUTH_SECRET
