# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        POSTGRES_DB: sure
        POSTGRES_USER: sure
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        DB_PORT: "5432"
        OIDC_CLIENT_ID: sure
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_ISSUER: https://auth.cloudjur.com/application/o/sure/
        OIDC_REDIRECT_URI: https://money.cloudjur.com/auth/openid_connect/callback
        MCP_USER_EMAIL: "{{ .MCP_USER_EMAIL }}"
        MCP_API_TOKEN: "{{ .MCP_API_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: sure
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: sure
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 12h
  data:
    - secretKey: MCP_USER_EMAIL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: MCP_USER_EMAIL
    - secretKey: MCP_API_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: MCP_API_TOKEN
    - secretKey: SECRET_KEY_BASE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: SECRET_KEY_BASE # openssl rand -hex 64
    - secretKey: OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: sure_oidc_id
    - secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: sure_oidc_secret
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: SURE_POSTGRES_PASSWORD
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
