# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        POSTGRES_DB: "sure"
        POSTGRES_USER: "sure"
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: SECRET_KEY_BASE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: SECRET_KEY_BASE # openssl rand -hex 64
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: SURE_POSTGRES_PASSWORD
