# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  values:
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      web:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: &img
              repository: ghcr.io/we-promise/sure
              tag: 0.7.1-hotfix.1@sha256:64fa5951bcd426863759f5f06cf0316522bc5ecb3552bb6894f4101ca8708f6f
            envFrom:
              - secretRef:
                  name: sure-secret

            env: &env
              TZ: Asia/Kuala_Lumpur
              PORT: &port 3000
              SELF_HOSTED: "true"
              ONBOARDING_STATE: open
              APP_DOMAIN: https://money.cloudjur.com
              RAILS_ASSUME_SSL: "true"
              RAILS_FORCE_SSL: "false"
              RAILS_ENV: production
              REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/10
              RAILS_MAX_THREADS: "1"
              MALLOC_ARENA_MAX: "1"
              AI_DEBUG_MODE: "false"
              OIDC_ISSUER: https://auth.cloudjur.com/application/o/sure/
              OIDC_REDIRECT_URI: https://money.cloudjur.com/auth/openid_connect/callback
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /up
                    port: &port 3000
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 6
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /up
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 2
                  failureThreshold: 6
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /up
                    port: *port
                  failureThreshold: 10
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext: &sec
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: sure-secret
          migration:
            image: *img
            command:
              - "bash"
              - "-lc"
            args: |
              DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rake db:prepare
            env: *env
            envFrom:
              - secretRef:
                  name: sure-secret
      worker:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: sure-secret
        containers:
          app:
            image: *img
            command:
              - bundle
              - exec
              - sidekiq
            envFrom:
              - secretRef:
                  name: sure-secret
            env: *env
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 1Gi
            securityContext: *sec

    service:
      web:
        controller: web
        ports:
          http:
            port: *port

    route:
      web:
        hostnames: [money.cloudjur.com]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: web
                port: *port
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Application Service
          gethomepage.dev/name: sure
          gethomepage.dev/description: Personal finance service
          gethomepage.dev/icon: https://raw.githubusercontent.com/chaijunkin/dashboard-icons/main/png/sure.png

    persistence:
      storage:
        existingClaim: sure
        advancedMounts:
          web:
            app:
              - path: /rails/storage
          worker:
            app:
              - path: /rails/storage
