# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
  namespace: downloads
spec:
  target:
    name: chaski-secret
    template:
      data:
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        RADARR_PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        SONARR_PUSHOVER_TOKEN: "{{ .SONARR_PUSHOVER_TOKEN }}"
  data:
    - secretKey: PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4f91b50a-243a-489d-bc8b-93504231f5d2
        property: app_key
    - secretKey: RADARR_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4f91b50a-243a-489d-bc8b-93504231f5d2
        property: radarr_api_token
    - secretKey: SONARR_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4f91b50a-243a-489d-bc8b-93504231f5d2
        property: sonarr_api_token
