# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: frontier-pool-3
spec:
  modelName: frontier-pool
  proxyRef: litellm
  params:
    model: openai/default
    apiBase: https://api.ilmu.ai/v1
    apiKey: os.environ/ILMU_API_KEY
    additional:
      order: 3
  info:
    mode: chat
    maxInputTokens: 131072
    maxOutputTokens: 16384
    supportsFunctionCalling: true
