# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: gemini-2.5-flash-lite
spec:
  modelName: gemini-2.5-flash-lite
  proxyRef: litellm
  params:
    model: openai/gemini-2.5-flash-lite
    apiBase: https://generativelanguage.googleapis.com/v1beta/openai
    apiKey: os.environ/GEMINI_API_KEY
  info:
    mode: chat
    maxInputTokens: 1048576
    maxOutputTokens: 65536
    supportsFunctionCalling: true
    supportsPromptCaching: true
    supportsVision: true
    extra:
      input_cost_per_token: 0.0000012500
      cache_read_input_token_cost: 0.0000003125
      output_cost_per_token: 0.0000100000
