# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: glm-5.1
spec:
  modelName: glm-5.1
  proxyRef: litellm
  params:
    model: zai/glm-5.1
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 204800
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
