# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: kimi-k2.6
spec:
  modelName: kimi-k2.6
  proxyRef: litellm
  params:
    model: moonshot/kimi-k2.6
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 262144
    maxOutputTokens: 262144
    supportsFunctionCalling: true
    supportsPromptCaching: true
