# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: memini-rerank
spec:
  modelName: memini-rerank
  proxyRef: litellm
  params:
    model: openai/memini-rerank
    apiBase: http://192.168.1.149:8736/v1
    apiKey: strix-halo
  info:
    mode: rerank
    extra:
      input_cost_per_token: 0.0
      output_cost_per_token: 0.0
