# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: ovh-wildcard
spec:
  modelName: ovh/*
  proxyRef: litellm
  params:
    model: openai/*
    apiBase: https://oai.endpoints.kepler.ai.cloud.ovh.net/v1
    additional:
      check_provider_endpoint: true
