# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: qwen3-asr
spec:
  modelName: qwen3-asr
  proxyRef: litellm
  params:
    model: openai/qwen3-asr
    apiBase: http://192.168.1.149:8739/v1
    apiKey: gufo-key
    additional:
      max_parallel_requests: 4
  info:
    mode: audio_transcription
    supportsFunctionCalling: false
    supportsVision: false
