# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: qwen3.6-plus
spec:
  modelName: qwen3.6-plus
  proxyRef: litellm
  params:
    model: dashscope/qwen3.6-plus
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 991808
    maxOutputTokens: 65536
    supportsFunctionCalling: true
    supportsPromptCaching: true
