---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: self-hosted
spec:
  modelName: self-hosted
  proxyRef: litellm
  params:
    model: openai/qwen3.8-flash-next-chat
    apiBase: http://192.168.1.149:8732/v1
    apiKey: halogen
  info:
    mode: chat
