# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: self-hosted
spec:
  modelName: self-hosted
  proxyRef: litellm
  params:
    model: openai/qwen/qwen3-4b-thinking-2507
    apiBase: http://jk-mac-mini.cloudjur.com:1234/v1
    apiKey: lm-studio
    additional:
      max_parallel_requests: 2
      order: 2
  info:
    mode: chat
    maxInputTokens: 262144
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    supportsVision: false
