---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: self-hosted-vision
spec:
  modelName: self-hosted-vision
  proxyRef: litellm
  params:
    model: openai/qwen3.8-flash-next
    apiBase: http://192.168.1.149:8732/v1
    apiKey: halogen
    additional:
      temperature: 0.7
      top_p: 0.8
      presence_penalty: 1.5
      repetition_penalty: 1.0
      reasoning_effort: none
      allowed_openai_params:
        - reasoning_effort
        - stream_options
  info:
    mode: chat
    maxInputTokens: 131072
    maxOutputTokens: 16384
    supportsFunctionCalling: false
    supportsVision: true
