# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: vercel-wildcard
spec:
  modelName: vercel/*
  proxyRef: litellm
  params:
    model: openai/*
    apiBase: https://ai-gateway.vercel.sh/v1
    apiKeyRef:
      name: litellm
      key: VERCEL_API_KEY
    dropParams: true
