# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./context7.yaml
  # - ./fli.yaml
  # - ./home-assistant.yaml
  - ./searxng.yaml
  # - ./sparkyfitness.yaml
  # - ./sure.yaml
