# yaml-language-server: $schema=https://crd.cloudjur.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: sparkyfitness
spec:
  alias: sparkyfitness
  proxyRef: litellm
  transport: http
  url: http://mcp-sparkyfitness-mcp-proxy.ai.svc.cluster.local:8080/mcp
