# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: hermes
    template:
      data:
        COMPOSIO_API_KEY: "{{ .COMPOSIO_API_KEY }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_BOT_TOKEN: "{{ .SAKE_BOT_TOKEN }}"
        DISCORD_HOME_CHANNEL: "{{ .SAKE_HOME_CHANNEL }}"
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_TOKEN }}"
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        TELEGRAM_HOME_CHANNEL: "{{ .TELEGRAM_ALLOWED_USERS }}"
        TELEGRAM_ALLOWED_USERS: "{{ .TELEGRAM_ALLOWED_USERS }}"
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
        MEMINI_API_KEY: "{{ .MEMINI_API_KEY }}"
  data:
    - secretKey: COMPOSIO_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: COMPOSIO_API_KEY
    - secretKey: DISCORD_ALLOWED_USERS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: DISCORD_ALLOWED_USERS
    - secretKey: SAKE_BOT_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: SAKE_BOT_TOKEN
    - secretKey: SAKE_HOME_CHANNEL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: SAKE_HOME_CHANNEL
    - secretKey: GITHUB_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: GITHUB_TOKEN
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: LITELLM_MASTER_KEY
    - secretKey: TELEGRAM_ALLOWED_USERS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: TELEGRAM_ALLOWED_USERS
    - secretKey: TELEGRAM_BOT_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: TELEGRAM_BOT_TOKEN
    - secretKey: MEMINI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: PLACEHOLDER_UUID_FOR_HERMES
        property: MEMINI_API_KEY
