hf_token: ENC[AES256_GCM,data:pKDyTZNOO5GuTkosjiobG2ZiygQr7NXd3PFD7gSB47DzLBMqiQ==,iv:mJvGBm5eu1HAss87XZkwnFDO4HC5gsCDuTl8Qbgayts=,tag:7CfBCG6CUfIQwio0U3mpjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOGpVdHNXUGRjUzZxaVlR
            OUxCN3RsR1NpY2ZvS0RnTUlqaENEVmJQV2pBCkQ3RlZOS0dSVXNvSzdoT0hrZHA0
            OWdXSTRxd1NONlRZOXIrcTV2OGg5N3cKLS0tIFh5ZGVBa0ZRaGg2TjhUYkhDdDJj
            RklPYytBR3NZWHNScy8zd0FNbm5LelUKlY5m0tZRvY85Lp1scy+UyG5jY7TZeLdU
            nj+QKzlKaaaZdEt8xbSCmAmV/eYF5hw1W7WR6mLwk4DsMuq/vHCN/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGh0eXJZczd5YzVsS3I2
            ZUFJeEtZb0VqaU84dExQTFJtVS9COGw4WEJjCnlFNlFQcDN1bWQrcEhrL0FzZW8w
            cmZsUVRiekNDeWExeWJBSXl6UGZWUE0KLS0tIHRndXlBb3ZEWGVJSWdwSjY3VDV4
            MC9yRHV4Qms0T0YyUHpad1plNEd4enMKjDmGhXrKYtQ4H8SgrBzOycj5v9MaZIzN
            sUh2mn9q45IqvjZFg4W6nwaQ1Zjc5vRI4/5W1wq0xDtKsoSy12/cLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13x3a0rdh5hnm4aj09melp3nmyqv5yyc4cvk4v6dsggehrck4gp7qhgzt8p
    lastmodified: "2026-10-02T20:18:09Z"
    mac: ENC[AES256_GCM,data:dHECyI8jeFaIDJgOKs5dbwJH46k9b6cOQwTvVWrcYONlblFS+lMH8NdqOomZcvSjMmbiylsQ3l6dn29XsbBgCcqjTTI3fDJ2wZTIibbmIr5Uyhb1FS+j2hCzY8/XMGex88mYx+MpG3v1K3XR9K3CVD79bVRyN/5QMOvMYmMTKnM=,iv:HLazu9SAXND7Hfz5qMD2c7dchepKkxwZprdWyj4GEP8=,tag:ag6YDGIgfBUbEPkeoA9/yg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
