# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name changedetection-secret
spec:
  refreshInterval: 12h
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .CHANGEDETECTION_PUSHOVER_TOKEN }}"
  data:
    - secretKey: PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4f91b50a-243a-489d-bc8b-93504231f5d2
        property: app_key
    - secretKey: CHANGEDETECTION_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4f91b50a-243a-489d-bc8b-93504231f5d2
        property: Default_api_token
