# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./k8s-monitoring/ks.yaml
  - ./exporters
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  # - ./external-access/ks.yaml # This is currently disabled as it is not yet fully working and needs some more work to be done on it.
  - ./kromgo/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./pyroscope/ks.yaml
  - ./silence-operator/ks.yaml
  - ./tempo/ks.yaml
  - ./webhook/ks.yaml
