# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MQTT_USERNAME: "{{ .MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
  refreshInterval: 1h
  data:
    - secretKey: MQTT_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9e81dd94-1b00-4f9b-be20-1cc468446d29
        property: username
    - secretKey: MQTT_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9e81dd94-1b00-4f9b-be20-1cc468446d29
        property: password
