# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        OIDC_CLIENT_ID: trek
        # "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  refreshInterval: 12h
  data:
    - secretKey: ADMIN_EMAIL
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: username
    - secretKey: ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: password
    - secretKey: ENCRYPTION_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: trek_encryption_key
    - secretKey: OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: trek_oidc_client_id
    - secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01a635df-c350-4eca-9f4f-6509ad2327c1
        property: trek_oidc_client_secret
