---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app trek
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
  upgrade:
    timeout: 2m
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostUsers: false
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            fsGroup: 65532
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile: {type: RuntimeDefault}

        containers:
          app:
            image:
              repository: mirror.gcr.io/mauriceboe/trek
              tag: 3.1.3@sha256:ae2198bf2133a9363fa8774f4666ba464c0c01ec4e30844f077d1c6116e3b6cb
            args:
              - sh
              - -c
              - cd /app/server && exec node --require tsconfig-paths/register dist/index.js
            env:
              NODE_ENV: production
              APP_URL: https://trips.cloudjur.com
              ALLOWED_ORIGINS: https://trips.cloudjur.com
              ALLOW_INTERNAL_NETWORK: true
              TRUST_PROXY: 1
              FORCE_HTTPS: true
              DEFAULT_LANGUAGE: en
              # LOG_LEVEL: debug
              TZ: "Asia/Kuala_Lumpur"
              ADMIN_EMAIL:
                secretKeyRef:
                  name: trek-secret
                  key: ADMIN_EMAIL
              ADMIN_PASSWORD:
                secretKeyRef:
                  name: trek-secret
                  key: ADMIN_PASSWORD
              ENCRYPTION_KEY:
                secretKeyRef:
                  name: trek-secret
                  key: ENCRYPTION_KEY
              OIDC_ONLY: false
              OIDC_ADMIN_CLAIM: groups
              OIDC_ADMIN_VALUE: admin
              OIDC_SCOPE: openid email profile
              OIDC_DISPLAY_NAME: Authentik
              OIDC_ISSUER: "https://auth.cloudjur.com/application/o/trek/"
              OIDC_DISCOVERY_URL: "https://auth.cloudjur.com/application/o/trek/.well-known/openid-configuration"
              OIDC_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: trek-secret
                    key: OIDC_CLIENT_ID
              OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: trek-secret
                    key: OIDC_CLIENT_SECRET

              # SMTP_HOST: smtp-relay.cluster-infra
              # SMTP_PORT: 25
              # SMTP_FROM: TREK <trek@cloudjur.com>
            probes:
              readiness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &port 3000
                    path: /api/health
              liveness: *probes
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile: {type: RuntimeDefault}
              capabilities: {drop: ["ALL"]}

    service:
      main:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames: ["trips.cloudjur.com"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Application Service
          gethomepage.dev/name: trek trips
          gethomepage.dev/icon: mdi-application
          gethomepage.dev/description: Travel Collaboration
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
            subPath: data
          - path: /app/uploads
            subPath: uploads
