# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app slskd
spec:
  interval: 1h # interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      slskd:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: Asia/Kuala_Lumpur
              SLSKD_APP_DIR: /config
              SLSKD_NO_VERSION_CHECK: true
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_SHARED_DIR: /media/Downloads/slskd/shared
              SLSKD_DOWNLOADS_DIR: /media/Downloads/slskd/complete
              SLSKD_INCOMPLETE_DIR: /media/Downloads/slskd/incomplete
              SLSKD_SHARE_FILTER: Thumbs.db$;\.DS_Store$
              SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50429
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 1Gi
        statefulset:
          volumeClaimTemplates:
            - name: config
              storageClass: local-hostpath
              accessMode: ReadWriteOnce
              size: 5Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "network",
            "ips": ["10.10.31.10/24"]
          }]
      # ,
      # "mac": "c6:58:f2:a7:62:ce"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
      soulseek:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.10.30.77
        ports:
          soulseek-tcp:
            port: *soulseekPort
            protocol: TCP
    configMaps:
      config:
        data:
          slskd.yml: |-
            directories:
              downloads: /media/Downloads/slskd/complete
              incomplete: /media/Downloads/slskd/incomplete
            permissions:
              file:
                mode: 750
            shares:
              directories:
                - /media/Downloads/slskd/shared
              filters:
                - \.ini$
                - Thumbs.db$
                - \.DS_Store$
    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
      media:
        type: nfs
        server: smb.cloudjur.com
        path: /tank/Storage
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - slskd.cloudjur.com
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - port: *port
                name: *app
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads Service
          gethomepage.dev/name: Slskd
          gethomepage.dev/description: Community File Sharing Service (Music)
          gethomepage.dev/icon: https://raw.githubusercontent.com/chaijunkin/dashboard-icons/main/png/cyberchef.png
