# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        # ACTUAL_PASSWORD: "{{ .ACTUAL_PASSWORD_SRC }}"
        # ACTUAL_SYNC_ID: "{{ .ACTUAL_SYNC_ID }}"
        # DISCORD_ADMIN_USER_ID: "{{ .DISCORD_ADMIN_USER_ID }}"
        # DISCORD_BOT_TOKEN: "{{ .MISO_BOT_TOKEN }}"
        # DISCORD_SERVER_ID: "{{ .DISCORD_SERVER_ID }}"
        # DISPATCH_AGENT_TOKEN: "{{ .DISPATCH_AGENT_TOKEN }}"
        # DISPATCH_URL: http://dispatch.llm:3000
        # GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        # MATCHA_BOT_TOKEN: "{{ .MATCHA_BOT_TOKEN }}"
        # MATCHA_CHANNEL_ID: "{{ .MATCHA_CHANNEL_ID }}"
        # MISO_GALLERY_API_KEY: "{{ .LLM_API_KEYS }}"
        # OPENAI_CODEX_USERNAME: "{{ .OPENAI_CODEX_USERNAME }}"
        # SAFFRON_BOT_TOKEN: "{{ .SAFFRON_BOT_TOKEN }}"
        # WEATHER_UNDERGROUND_API_KEY: "{{ .WEATHER_UNDERGROUND_API_KEY }}"
        CONTEXT7_API_KEY: "{{ .OPENCLAW_API_KEY }}"
        MEMINI_API_KEY: "{{ .MEMINI_API_KEY }}"
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c5984ae4-aa34-4825-8f83-bef9827dc69d
        property: OPENCLAW_GATEWAY_TOKEN
    # - secretKey: ACTUAL_PASSWORD_SRC
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: ACTUAL_PASSWORD_SRC
    # - secretKey: ACTUAL_SYNC_ID
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: ACTUAL_SYNC_ID
    # - secretKey: DISCORD_ADMIN_USER_ID
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: DISCORD_ADMIN_USER_ID
    # - secretKey: MISO_BOT_TOKEN
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: MISO_BOT_TOKEN
    # - secretKey: DISCORD_SERVER_ID
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: DISCORD_SERVER_ID
    # - secretKey: DISPATCH_AGENT_TOKEN
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: DISPATCH_AGENT_TOKEN
    # - secretKey: GITHUB_TOKEN
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: GITHUB_TOKEN
    - secretKey: LITELLM_MASTER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bf2fcc14-bd51-4122-9445-53dacdfb1d69
        property: LITELLM_MASTER_KEY
    # - secretKey: MATCHA_BOT_TOKEN
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: MATCHA_BOT_TOKEN
    # - secretKey: MATCHA_CHANNEL_ID
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: MATCHA_CHANNEL_ID
    # - secretKey: LLM_API_KEYS
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: LLM_API_KEYS
    # - secretKey: OPENAI_CODEX_USERNAME
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: OPENAI_CODEX_USERNAME
    # - secretKey: SAFFRON_BOT_TOKEN
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: SAFFRON_BOT_TOKEN
    # - secretKey: WEATHER_UNDERGROUND_API_KEY
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: c5984ae4-aa34-4825-8f83-bef9827dc69d
    #     property: WEATHER_UNDERGROUND_API_KEY
    - secretKey: OPENCLAW_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f70e550d-01b3-4ab7-8329-339461d33741
        property: context7-api-key
    - secretKey: MEMINI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5b8f5c59-8a9c-495b-9f40-9ea2a2ab249f
        property: api_key
