# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_DBHOST: &dbHost postgres-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: &dbUser paperless
        PAPERLESS_DBPASS: &dbPass "{{ .dbPass }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "{{ .PAPERLESS_OAUTH_CLIENT_ID }}",
                  "secret": "{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://auth.cloudjur.com/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ]
            }
          }
        PAPERLESS_ADMIN_USER: |-
          {{ .adminUserName }}
        PAPERLESS_ADMIN_PASSWORD: |-
          {{ .adminPassword }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 12h
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    - secretKey: dbPass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce0161ae-6d5b-4210-88a0-e46097b87733
        property: dbPass
        # - secretKey: redis_url
        #   sourceRef:
        #     storeRef:
        #       name: bitwarden-fields
        #       kind: ClusterSecretStore
        #   remoteRef:
        #     key: ce0161ae-6d5b-4210-88a0-e46097b87733
        #     property: redis_url
    - secretKey: adminUserName
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ce0161ae-6d5b-4210-88a0-e46097b87733
        property: username
    - secretKey: adminPassword
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ce0161ae-6d5b-4210-88a0-e46097b87733
        property: password
    - secretKey: PAPERLESS_OAUTH_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce0161ae-6d5b-4210-88a0-e46097b87733
        property: PAPERLESS_OAUTH_CLIENT_ID
    - secretKey: PAPERLESS_OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce0161ae-6d5b-4210-88a0-e46097b87733
        property: PAPERLESS_OAUTH_CLIENT_SECRET
    - secretKey: PAPERLESS_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ce0161ae-6d5b-4210-88a0-e46097b87733
        property: PAPERLESS_SECRET_KEY
