apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-default-vault-smb-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb
  volumeName: hass-default-vault-smb-pv
