# yaml-language-server: $schema=https://crd.cloudjur.com/toolhive.stacklok.dev/mcpserverentry_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServerEntry
metadata:
  name: grafana
spec:
  remoteUrl: http://mcp-grafana.observability.svc.cluster.local:8000/sse
  transport: sse
  groupRef:
    name: mcp-tools
