# yaml-language-server: $schema=https://crd.cloudjur.com/kopiur.home-operations.com/snapshot_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Snapshot
metadata:
  name: ${APP}-adhoc
spec:
  policyRef:
    name: ${APP}
  tags:
    reason: manual
