# yaml-language-server: $schema=https://crd.cloudjur.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h # interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    serviceMonitor:
      create: true
    web:
      config:
        authentication:
          type: Anonymous
          anonymous:
            username: flux
            groups:
              - flux-admin
      httpRoute:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Platform Infrastructure
          gethomepage.dev/name: Flux Operator
          gethomepage.dev/icon: flux.png
        hostnames:
          - flux-operator.cloudjur.com
        parentRefs:
          - name: envoy-internal
            namespace: network
      networkPolicy:
        create: false
