# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app changedetection
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/changedetection/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: storage
    - name: kopiur
      namespace: storage
  components:
    # - ../../../../components/volsync
    - ../../../../components/kopiur/backup
    - ../../../../components/kopiur/remote
      # - ../../../../components/kopiur/adhoc-snapshot
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_PUID: "1000"
      KOPIUR_PGID: "1000"
      KOPIUR_NONROOT: "true"
  prune: true
  wait: false
  interval: 30m
