# yaml-language-server: $schema=https://crd.cloudjur.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trivy-operator-polr-adapter
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/chaijunkin/charts-mirror/trivy-operator-polr-adapter
  ref:
    tag: 0.11.1
---
# yaml-language-server: $schema=https://crd.cloudjur.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator-polr-adapter
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: trivy-operator-polr-adapter
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    serviceMonitor:
      enabled: true
    crds:
      install: true
