# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: terraform-backend-secret
spec:
  externalSecretName: terraform-backend-secret
  namespaceSelectors:
    - matchLabels:
        terraform-shared-credentials: "true"
  externalSecretSpec:
    target:
      name: terraform-backend-secret
      template:
        data:
          access_key: "{{ .R2_ACCESS_KEY }}"
          secret_key: "{{ .R2_ACCESS_SECRET }}"
    data:
      - secretKey: R2_ACCESS_KEY
        sourceRef:
          storeRef:
            name: bitwarden-fields
            kind: ClusterSecretStore
        remoteRef:
          key: cb424eb9-ca32-4608-93ef-63e28c3f531e
          property: r2_access_key
      - secretKey: R2_ACCESS_SECRET
        sourceRef:
          storeRef:
            name: bitwarden-fields
            kind: ClusterSecretStore
        remoteRef:
          key: cb424eb9-ca32-4608-93ef-63e28c3f531e
          property: r2_access_secret
---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tofu-branch-token
spec:
  target:
    name: tofu-branch-token
    template:
      data:
        token: "{{ .github_pat }}"
  data:
    - secretKey: github_pat
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b67e4583-a622-4cf2-a172-58ee67c703da
        property: github_pat
