# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  cloud {
    organization = "chaijunkin"
    workspaces { name = "minio-workspace" }
  }
  required_providers {
    minio = {
      source  = "aminueza/minio"
      version = "3.6.3"
    }
  }
}
provider "minio" {
  alias          = "nas"
  minio_server   = var.minio_server
  minio_user     = var.minio_user
  minio_password = var.minio_password
}
