# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  cloud {
    organization = "chaijunkin"
    workspaces { name = "minio-workspace" }
  }
  required_providers {
    b2 = {
      source  = "Backblaze/b2"
      version = "0.8.12"
    }

    minio = {
      source  = "aminueza/minio"
      version = "2.2.1"
    }
  }
}
provider "minio" {
  alias          = "nas"
  minio_server   = var.minio_server
  minio_user     = var.minio_user
  minio_password = var.minio_password
}
