# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # OIDC
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"

  refreshInterval: 12h
  data:
    - secretKey: OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b9595df9-620e-49ee-a9f7-4a408a6839ba
        property: oidc_client_id
    - secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        # TODO: Replace with the actual Bitwarden UUID for Kanidm/Authentik OIDC Secret
        key: b9595df9-620e-49ee-a9f7-4a408a6839ba
        property: oidc_client_secret
