---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: mealie-configmap
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - resources/logconf.json
configurations:
  - resources/kustomizeconfig.yaml
