# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-config
spec:
  refreshInterval: 1h
  target:
    name: rclone-config-secret
    template:
      templateFrom:
        - configMap:
            name: rclone-config-tpl
            items:
              - key: rclone.conf
  data:
    - secretKey: B2_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6c0aa741-020a-4a97-83d6-a2528dfe177a
        property: b2_application_key
    - secretKey: B2_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6c0aa741-020a-4a97-83d6-a2528dfe177a
        property: b2_application_key_id
    - secretKey: GARAGE_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GARAGE_KEY_ID
    - secretKey: GARAGE_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d10ce5c3-ce4b-4f22-9430-b962390e0cba
        property: GARAGE_SECRET_KEY
    # - secretKey: B2_ENDPOINT
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: 6c0aa741-020a-4a97-83d6-a2528dfe177a
    #     property: B2_ENDPOINT
    # - secretKey: B2_REGION
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: 6c0aa741-020a-4a97-83d6-a2528dfe177a
    #     property: B2_REGION

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rclone-secret
spec:
  target:
    name: *name
    template:
      data:
        RCLONE_RC_USER: "{{ .RCLONE_USER }}"
        RCLONE_RC_PASS: "{{ .RCLONE_PASS }}"
  data:
    - secretKey: RCLONE_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 109cd97c-d275-425f-b5d1-956a73f2c720
        property: username
    - secretKey: RCLONE_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 109cd97c-d275-425f-b5d1-956a73f2c720
        property: password
