---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rclone
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      *app :
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: &img
              repository: ghcr.io/rclone/rclone
              tag: 1.74.3@sha256:623378ad0ff3ebd5cebf77720843c0e02edfe46e2d5b5ac6bed54c6371780dfb
            args:
              - "rcd"
              - "--rc-web-gui"
              - "--rc-web-gui-update"
              - "--rc-web-gui-force-update"
              - "--rc-web-gui-no-open-browser"
              - "--rc-addr=:$(HTTP_PORT)"
              - "--rc-enable-metrics"
              - "--metrics-addr=:$(METRICS_PORT)"
              - "--log-level=INFO"
              - "--exclude=locks/**"
            env: &env
              HTTP_PORT: &port 8080
              METRICS_PORT: &metrics 9090
              RCLONE_URL: http://rclone.storage.svc.cluster.local:8080/
              RCLONE_MULTI_THREAD_CUTOFF: "0"
              RCLONE_MULTI_THREAD_STREAMS: "1"
            envFrom: &envFrom
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources: &res
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext: &sc
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
      b2-vw-to-local: &cron1
        type: cronjob
        cronjob: &cj
          schedule: "@daily"
          concurrencyPolicy: Replace
          ttlSecondsAfterFinished: 86400
          failedJobsHistory: 1
          backoffLimit: 2
        containers:
          app: &rclct
            image: *img
            command: ["/bin/sh", "-c", "rclone rc $(ARG)"]
            env: &envcr
              <<: *env
              RCLONE_TIMEOUT: 1h
              ARG:
                | # TODO: so much jank over k8s doing auto shell escaping on args and me wanting to not repeat the command line
                sync/sync srcFs='b2:${B2_VW_BUCKET}' dstFs='/data/S3/B2/' _config='{"Progress": true}'
            envFrom: *envFrom
            securityContext: *sc
        pod:
          annotations: &cran
            reloader.stakater.com/auto: "false"
          resources: *res
        annotations: *cran
      b2-vw-to-r2: &cron1
        type: cronjob
        cronjob: &cj
          schedule: "@daily"
          concurrencyPolicy: Replace
          ttlSecondsAfterFinished: 86400
          failedJobsHistory: 1
          backoffLimit: 2
        containers:
          app: &rclct
            image: *img
            command: ["/bin/sh", "-c", "rclone rc $(ARG)"]
            env: &envcr
              <<: *env
              RCLONE_TIMEOUT: 1h
              ARG:
                | # TODO: so much jank over k8s doing auto shell escaping on args and me wanting to not repeat the command line
                sync/sync srcFs='b2:${B2_VW_BUCKET}' dstFs='r2:${B2_VW_BUCKET}' _config='{"Progress": true}'
            envFrom: *envFrom
            securityContext: *sc
        pod:
          annotations: &cran
            reloader.stakater.com/auto: "false"
          resources: *res
        annotations: *cran
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.cloudjur.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: secret
        name: "{{ .Release.Name }}-config-secret"
        advancedMounts:
          *app :
            app:
              - path: "/.rclone.conf"
                subPath: "rclone.conf"
      data:
        type: nfs
        server: smb.cloudjur.com
        path: /tank/Backup/
        globalMounts:
          - path: /data
      cache:
        type: emptyDir
        advancedMounts:
          *app :
            app:
              - path: /.cache
                subPath: cache
      tmp:
        type: emptyDir
