# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-anubis-key
spec:
  refreshInterval: 12h
  target:
    name: ${APP}-anubis-key-secret
    creationPolicy: Owner
    template:
      data:
        ED25519_PRIVATE_KEY_HEX: "{{ .anubis_ed25519_private_key_hex }}"
  data:
    - secretKey: anubis_ed25519_private_key_hex
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${APP_KEY_ID}
        property: ed25519_private_key_hex
