# yaml-language-server: $schema=https://crd.cloudjur.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: observability
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: kube-prometheus-stack
  dependsOn:
    - name: local-hostpath
      namespace: storage
    - name: openebs
      namespace: storage
  path: ./kubernetes/apps/observability/kube-prometheus-stack/app
  prune: true
  # postBuild:
  #   substitute:
  #     APP: *app
  #     EXT_AUTH_TARGET: prometheus-ext
  #     EXT_AUTH_TARGET_2: alertmanager-ext
  #     EXT_AUTH_BACKEND_REF: authentik-server
  # components:
  #   - ../../../../components/ext-auth
  #   - ../../../../components/ext-auth/two
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 24h
  retryInterval: 1m
  timeout: 5m
