# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sure-mcp-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        MCP_API_TOKEN: "{{ .MCP_API_TOKEN }}"
  data:
    - secretKey: MCP_API_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: mcp_token
