# yaml-language-server: $schema=https://crd.cloudjur.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: sure-mcp
spec:
  image: node:24-alpine
  transport: stdio
  groupRef:
    name: mcp-tools
  podTemplateSpec:
    spec:
      volumes:
        - name: mcp-bin
          emptyDir: {}
      initContainers:
        - name: install-mcp-remote
          image: node:24-alpine
          command:
            - sh
            - -c
            - "npm install --prefix /mcp mcp-remote"
          volumeMounts:
            - name: mcp-bin
              mountPath: /mcp
      containers:
        - name: mcp
          volumeMounts:
            - name: mcp-bin
              mountPath: /mcp
          securityContext:
            readOnlyRootFilesystem: false
          env:
            - name: MCP_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sure-mcp-secret
                  key: MCP_API_TOKEN
          command:
            - node
          args:
            - /mcp/node_modules/.bin/mcp-remote
            - http://sure.default.svc.cluster.local:3000/mcp
            - --allow-http
            - --transport
            - http-only
            - --header
            - "Authorization: Bearer $(MCP_API_TOKEN)"
