---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-backup
  namespace: jobs
spec:
  refreshInterval: 12h
  target:
    name: opnsense-backup
    template:
      data:
        OPNSENSE_KEY: "{{ .OPNSENSE_API_KEY }}"
        OPNSENSE_SECRET: "{{ .OPNSENSE_API_SECRET }}"
  data:
    - secretKey: OPNSENSE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ecec2bfa-7f56-469d-96eb-d28e99d845b5
        property: api_key
    - secretKey: OPNSENSE_API_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ecec2bfa-7f56-469d-96eb-d28e99d845b5
        property: api_secret
