---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode
spec:
  target:
    name: opencode
    template:
      type: Opaque
      data:
        CONTEXT7_API_KEY: "{{ .CONTEXT7_OPENCODE_API_KEY }}"
        GH_TOKEN: "{{ .GITHUB_TOKEN }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        LITELLM_API_KEY: "{{ .LITELLM_OPENCODE_API_KEY }}"
        MEMINI_API_KEY: "{{ .MEMINI_API_KEY }}"
        OPENCODE_SERVER_PASSWORD: "{{ .OPENCODE_SERVER_PASSWORD }}"
  refreshInterval: 12h
  data:
    - secretKey: CONTEXT7_OPENCODE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f70e550d-01b3-4ab7-8329-339461d33741
        property: context7-api-key
    - secretKey: GITHUB_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b67e4583-a622-4cf2-a172-58ee67c703da
        property: github_pat
    - secretKey: LITELLM_OPENCODE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bf2fcc14-bd51-4122-9445-53dacdfb1d69
        property: LITELLM_VIRTUAL_KEY
    - secretKey: MEMINI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5b8f5c59-8a9c-495b-9f40-9ea2a2ab249f
        property: api_key
    - secretKey: OPENCODE_SERVER_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 670fd45c-eb15-49a8-af24-8ac619adfefb
        property: password
---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode-oidc
spec:
  target:
    name: opencode-oidc
    template:
      type: Opaque
      data:
        client-id: "opencode"
        client-secret: "{{ .OPENCODE_CLIENT_SECRET }}"
  refreshInterval: 12h
  data:
    # - secretKey: OPENCODE_CLIENT_ID
    #   sourceRef:
    #     storeRef:
    #       name: bitwarden-fields
    #       kind: ClusterSecretStore
    #   remoteRef:
    #     key: 670fd45c-eb15-49a8-af24-8ac619adfefb
    #     property: opencode_client_id
    - secretKey: OPENCODE_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 670fd45c-eb15-49a8-af24-8ac619adfefb
        property: opencode_client_secret
---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode-htpasswd
spec:
  target:
    name: opencode-htpasswd
    template:
      type: Opaque
      data:
        # To generate an htpasswd string, run:
        # htpasswd -nb <username> <password>
        # OR: echo "admin:$(openssl passwd -5 mysecurepassword)"
        .htpasswd: "{{ .HTPASSWD }}"
  refreshInterval: 12h
  data:
    - secretKey: HTPASSWD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 670fd45c-eb15-49a8-af24-8ac619adfefb
        property: opencode_htpasswd
---
# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode-ssh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-ssh
  target:
    name: *name
    template:
      data:
        id_ed25519: "{{ .opencode_ssh_private_key }}"
        id_ed25519.pub: "{{ .opencode_ssh_public_key }}"
  data:
    - secretKey: opencode_ssh_private_key
      sourceRef:
        storeRef:
          name: bitwarden-ssh
          kind: ClusterSecretStore
      remoteRef:
        key: 29557c08-8e03-4ba1-a74b-75ae29b8dcc5
        property: privateKey
    - secretKey: opencode_ssh_public_key
      sourceRef:
        storeRef:
          name: bitwarden-ssh
          kind: ClusterSecretStore
      remoteRef:
        key: 29557c08-8e03-4ba1-a74b-75ae29b8dcc5
        property: publicKey
