# yaml-language-server: $schema=https://crd.cloudjur.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: default-vault-smb-secret
spec:
  target:
    name: default-vault-smb-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  refreshInterval: 12h
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        # TODO: replace with your Bitwarden/1Password item UUID
        key: 2df6bc0c-f02e-4527-a079-86330bc3748e
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2df6bc0c-f02e-4527-a079-86330bc3748e
        property: password
